import Head from 'next/head'

import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

type Props = {
    title?:string
    fileName?:string
    children?: ReactNode
}

export default function LayoutHome({title, children }: Props) {
    return (
        <>
            <Head>
                <title>{title ?? 'simi'}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                {children}
            </main>
        </>
    )
}